apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: boost-ui-config
parameters:
- description: Defines the namespace within which these objects are deployed
  name: NAMESPACE
  required: true
- description: Defines name of the microservice
  name: MICROSERVICE
  required: true
- description: Defines max memory
  name: MAX_MEMORY
  required: true
- description: Defines min memory
  name: MIN_MEMORY
  required: true
- description: Defines max cpu
  name: MAX_CPU
  required: true
- description: Defines min memory
  name: MIN_CPU
  required: true
- description: Defines number of replicas
  name: REPLICAS
  required: true
- description: Defines the namespace for the image stream
  name: DOCKER_NAMESPACE
  required: true
- description: Defines docker registry
  name: DOCKER_REGISTRY
  required: true
- description: Defines docker registry
  name: DOCKER_IMAGE_LABEL
  required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${MICROSERVICE}
    name: ${MICROSERVICE}
    namespace: ${NAMESPACE}
  spec:
    replicas: "${{REPLICAS}}"
    revisionHistoryLimit: 10
    selector:
      app: ${MICROSERVICE}
      deploymentconfig: ${MICROSERVICE}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${MICROSERVICE}
          deploymentconfig: ${MICROSERVICE}
      spec:
        containers:
          - env:
              - name: PRODUCT
                valueFrom:
                  configMapKeyRef:
                    name: ${MICROSERVICE}
                    key: PRODUCT
              - name: PRODUCT_DESCRIPTION
                valueFrom:
                  configMapKeyRef:
                    name: ${MICROSERVICE}
                    key: PRODUCT_DESCRIPTION
              - name: TASK_MANAGEMENT_TITLE
                valueFrom:
                  configMapKeyRef:
                    name: ${MICROSERVICE}
                    key: TASK_MANAGEMENT_TITLE
              - name: GATEWAY_API_SERVICE_URI
                valueFrom:
                  configMapKeyRef:
                    name: ${MICROSERVICE}
                    key: GATEWAY_API_SERVICE_URI
            image: ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${MICROSERVICE}:${DOCKER_IMAGE_LABEL}
            imagePullPolicy: Always
            name: ${MICROSERVICE}
            ports:
              - containerPort: 8778
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
            readinessProbe:
              failureThreshold: 10
              initialDelaySeconds: 30
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 1
              httpGet:
                path: /api/health
                port: 8080
                scheme: HTTP
            resources:
              limits:
                cpu: ${MAX_CPU}
                memory: ${MAX_MEMORY}
              requests:
                cpu: ${MIN_CPU}
                memory: ${MIN_MEMORY}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${MICROSERVICE}
    name: ${MICROSERVICE}
    namespace: ${NAMESPACE}
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: 8778-tcp
        port: 8778
        protocol: TCP
        targetPort: 8778
    selector:
      app: ${MICROSERVICE}
      deploymentconfig: ${MICROSERVICE}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}